### ISSUE TITLE
Add publications to publication list

### ISSUE THREAD

**Issue by jelletreep** [UtrechtUniversity/research-engineering#2]
Create a list of academic papers where our team contributed. Plain list? APA format? Perhaps also a separate list with non academic publications?

**Comment by qubixes** [comment]
Format for publicaties:

{Names}, {Title} {Journal in italic} {volume in bold}, {page nr(s)} (year)

Example:

Karsai, M., Perra, N. & Vespignani, A. Time varying networks and the weakness of strong ties. _Scientific reports_ **4**, 4001 (2014)

**Comment by jelletreep** [comment]
IJsseldijk, L. L., Hessing, S., Mairo, A., Ten Doeschate, M. T., Treep, J., van den Broek, J., Keijl, G. O., Siebert, U., Heesterbeek, H., Gröne, A. & Leopold, M. F. [Nutritional status and prey energy density govern reproductive success in a small cetacean.](https://doi.org/10.1038/s41598-021-98629-x) _Scientific reports_, **11**, 1-13 (2021)

Schuller, B. W., Batliner, A., Bergler, C., Mascolo, C, ... , Zwerts, J., Treep, J. & Kaandorp, C. [The INTERSPEECH 2021 Computational Paralinguistics Challenge: COVID-19 cough, COVID-19 speech, escalation & primates.](https://arxiv.org/abs/2102.13468) _arXiv preprint_ **arXiv:2102.13468** (2021)

Zwerts, J. A., Treep, J., Kaandorp, C. S., Meewis, F., Koot, A. C., & Kaya, H. [Introducing a central african primate vocalisation dataset for automated species classification.](https://arxiv.org/abs/2101.10390) _arXiv preprint_ **arXiv:2101.10390** (2021)

**Comment by jelletreep** [comment]
Idea to add the name of the RSE in the author list in bold?
e.g.

Karsai, M., **Perra, N.** & Vespignani, A. [Time varying networks and the weakness of strong ties.](https://doi.org/10.1038/srep04001) _Scientific reports_ **4**, 4001 (2014)

**Comment by qubixes** [comment]
Personally, I don't think that is necessary. Although, I could see a case for splitting the list into two; one for publications that we have authored and another that we have just collaborated on?

**Comment by qubixes** [comment]
I have added the citations from Martine and Jelle.

**Comment by qubixes** [comment]
I'll assume that for now all the publications are in there. If more need to be added, just create a pull request and add me as a reviewer. I'll close the issue for now.
