### ISSUE TITLE
Update Snellius - iRODS iCommands guide

### ISSUE THREAD

**Issue by RoelBrouwer** [UtrechtUniversity/research-engineering#47]
- [x] Update 'module load' statements to more recent module environments *
- [x] Add a little explanation on what the path to the YODA folder should exactly look like (`i:my_yoda_input_directory` - does it include the group folder, instance name, etc.? - i.e., what is the default 'current' YODA folder)

\* Specifically, this should be replaced:
```sh
module load 2020
module load icommands
```
should become
```sh
module load 2022
module load iRODS-iCommands/4.3.0
```

**Comment by jelletreep** [comment]
Fixed! @RoelBrouwer can you open a PR
Then I can merge
