### ISSUE TITLE
Update project list

### ISSUE THREAD

**Issue by jelletreep** [UtrechtUniversity/research-engineering#49]
Please add any new projects that don't exist yet on the list. The list is located in the `_pages/projects` folder. Please create a branch and a pull request when you have added the project. We might also consider add some projects that are not formally an engineering project (VRE, ibridges, Whisper, etc.) Just add them if you think they are a good addition to the list and we can discuss it in the PR.

- [x] Martine
- [x] Modhurita
- [x] Roel
- [x] Maarten
- [x] Christine
- [x] Parisa
- [x] Shiva
- [x] Raoul
- [x] Dawa
- [x] Jelle

**Comment by ShNadi** [comment]
Updated!

**Comment by qubixes** [comment]
@jelletreep We/you might want to finish this PR?
