### ISSUE TITLE
Review "landing page"

### ISSUE THREAD

**Issue by RoelBrouwer** [UtrechtUniversity/research-engineering#5]
We (probably) want to use the main page to trigger the interest of the viewer, and point them to where they want to go as quickly as possible. It may not be necessary to make a landing page that complies with all best practices from the marketing world, but I do think it may be useful to consider it at least a little bit.

A few points we could consider for the landing page:

- It has to be simple. Not to much information, buttons or other elements. Just a few things that attract attention/show our team, make clear what can be found on the site, and a way to get there.
- Any essential elements should be "above the fold", i.e. immediately visible when the page is first loaded.
- Walls of text are rarely read.

I would say that we use the top of our main page to briefly introduce our team (a descriptive title with a one or two sentence(s) long description of our team), show some visual elements (team picture/pictures that express what we do) and present navigation elements that point to more detailed information. Partially, this could be further down on the same page (internal link) or on a separate page.

Once we have a clear definition of services (etc.) that we provide (like we discussed before, and will probably talk about on Thursday), it would be good to present this on the main page too (although not in the top bit, probably just below), in some clear/structured/table-like way with more detailed information on each service on a separate page that is just one click away.

These are just some initial thoughts. Again, we do not have to go all the way to make our site a high-conversion piece of eye candy. But making it at least a little attractive and easy to navigate would be a good move in my opinion.

The "two-stage rocket" setup with the RDM page does complicate matters a little, as the RDM page is the first thing anybody sees when looking for information on our team.

**Comment by hailihu** [comment]
I was looking trough some [RSE websites](https://society-rse.org/community/rse-groups/), and found [this one](https://www.ucl.ac.uk/research-it-services/research-software-developmen) quite nice . It ticks most boxes @RoelBrouwer described.

**Comment by hailihu** [comment]
Most comments above are now dealt with. I am closing this comment and propose making new (atomic) issues specifically targeted to current landing page for further improvements.
